/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as ForbiddenIndexRouteImport } from './routes/forbidden/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AuthenticatedRaidRunIndexRouteImport } from './routes/_authenticated/raid-run/index'
import { Route as AuthenticatedRaidRunIdRouteImport } from './routes/_authenticated/raid-run/$id'
import { Route as AuthenticatedAdminAppSettingsIndexRouteImport } from './routes/_authenticated/admin/app-settings/index'
import { Route as AuthenticatedAdminGameDungeonsIndexRouteImport } from './routes/_authenticated/admin/game-dungeons/index'
import { Route as AuthenticatedAdminGameExpansionsIndexRouteImport } from './routes/_authenticated/admin/game-expansions/index'
import { Route as AuthenticatedAdminGameItemsIndexRouteImport } from './routes/_authenticated/admin/game-items/index'
import { Route as AuthenticatedAdminGameServersIndexRouteImport } from './routes/_authenticated/admin/game-servers/index'
import { Route as AuthenticatedAdminIdiomsIndexRouteImport } from './routes/_authenticated/admin/idioms/index'
import { Route as AuthenticatedAdminKungfusIndexRouteImport } from './routes/_authenticated/admin/kungfus/index'
import { Route as AuthenticatedAdminRaidRunsIndexRouteImport } from './routes/_authenticated/admin/raid-runs/index'
import { Route as AuthenticatedAdminRaidSignupsIndexRouteImport } from './routes/_authenticated/admin/raid-signups/index'
import { Route as AuthenticatedAdminSchoolsIndexRouteImport } from './routes/_authenticated/admin/schools/index'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin/users/index'
import { Route as AuthenticatedGameAssistGuessIdiomIndexRouteImport } from './routes/_authenticated/game-assist/guess-idiom/index'
import { Route as AuthenticatedGameAssistMinesweeperIndexRouteImport } from './routes/_authenticated/game-assist/minesweeper/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ForbiddenIndexRoute = ForbiddenIndexRouteImport.update({
  id: '/forbidden/',
  path: '/forbidden/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRaidRunIndexRoute =
  AuthenticatedRaidRunIndexRouteImport.update({
    id: '/raid-run/',
    path: '/raid-run/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRaidRunIdRoute = AuthenticatedRaidRunIdRouteImport.update({
  id: '/raid-run/$id',
  path: '/raid-run/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAppSettingsIndexRoute =
  AuthenticatedAdminAppSettingsIndexRouteImport.update({
    id: '/app-settings/',
    path: '/app-settings/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminGameDungeonsIndexRoute =
  AuthenticatedAdminGameDungeonsIndexRouteImport.update({
    id: '/game-dungeons/',
    path: '/game-dungeons/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminGameExpansionsIndexRoute =
  AuthenticatedAdminGameExpansionsIndexRouteImport.update({
    id: '/game-expansions/',
    path: '/game-expansions/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminGameItemsIndexRoute =
  AuthenticatedAdminGameItemsIndexRouteImport.update({
    id: '/game-items/',
    path: '/game-items/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminGameServersIndexRoute =
  AuthenticatedAdminGameServersIndexRouteImport.update({
    id: '/game-servers/',
    path: '/game-servers/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminIdiomsIndexRoute =
  AuthenticatedAdminIdiomsIndexRouteImport.update({
    id: '/idioms/',
    path: '/idioms/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminKungfusIndexRoute =
  AuthenticatedAdminKungfusIndexRouteImport.update({
    id: '/kungfus/',
    path: '/kungfus/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRaidRunsIndexRoute =
  AuthenticatedAdminRaidRunsIndexRouteImport.update({
    id: '/raid-runs/',
    path: '/raid-runs/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRaidSignupsIndexRoute =
  AuthenticatedAdminRaidSignupsIndexRouteImport.update({
    id: '/raid-signups/',
    path: '/raid-signups/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSchoolsIndexRoute =
  AuthenticatedAdminSchoolsIndexRouteImport.update({
    id: '/schools/',
    path: '/schools/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedGameAssistGuessIdiomIndexRoute =
  AuthenticatedGameAssistGuessIdiomIndexRouteImport.update({
    id: '/game-assist/guess-idiom/',
    path: '/game-assist/guess-idiom/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGameAssistMinesweeperIndexRoute =
  AuthenticatedGameAssistMinesweeperIndexRouteImport.update({
    id: '/game-assist/minesweeper/',
    path: '/game-assist/minesweeper/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/forbidden/': typeof ForbiddenIndexRoute
  '/login/': typeof LoginIndexRoute
  '/raid-run/$id': typeof AuthenticatedRaidRunIdRoute
  '/raid-run/': typeof AuthenticatedRaidRunIndexRoute
  '/admin/app-settings/': typeof AuthenticatedAdminAppSettingsIndexRoute
  '/admin/game-dungeons/': typeof AuthenticatedAdminGameDungeonsIndexRoute
  '/admin/game-expansions/': typeof AuthenticatedAdminGameExpansionsIndexRoute
  '/admin/game-items/': typeof AuthenticatedAdminGameItemsIndexRoute
  '/admin/game-servers/': typeof AuthenticatedAdminGameServersIndexRoute
  '/admin/idioms/': typeof AuthenticatedAdminIdiomsIndexRoute
  '/admin/kungfus/': typeof AuthenticatedAdminKungfusIndexRoute
  '/admin/raid-runs/': typeof AuthenticatedAdminRaidRunsIndexRoute
  '/admin/raid-signups/': typeof AuthenticatedAdminRaidSignupsIndexRoute
  '/admin/schools/': typeof AuthenticatedAdminSchoolsIndexRoute
  '/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/game-assist/guess-idiom/': typeof AuthenticatedGameAssistGuessIdiomIndexRoute
  '/game-assist/minesweeper/': typeof AuthenticatedGameAssistMinesweeperIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/forbidden': typeof ForbiddenIndexRoute
  '/login': typeof LoginIndexRoute
  '/raid-run/$id': typeof AuthenticatedRaidRunIdRoute
  '/raid-run': typeof AuthenticatedRaidRunIndexRoute
  '/admin/app-settings': typeof AuthenticatedAdminAppSettingsIndexRoute
  '/admin/game-dungeons': typeof AuthenticatedAdminGameDungeonsIndexRoute
  '/admin/game-expansions': typeof AuthenticatedAdminGameExpansionsIndexRoute
  '/admin/game-items': typeof AuthenticatedAdminGameItemsIndexRoute
  '/admin/game-servers': typeof AuthenticatedAdminGameServersIndexRoute
  '/admin/idioms': typeof AuthenticatedAdminIdiomsIndexRoute
  '/admin/kungfus': typeof AuthenticatedAdminKungfusIndexRoute
  '/admin/raid-runs': typeof AuthenticatedAdminRaidRunsIndexRoute
  '/admin/raid-signups': typeof AuthenticatedAdminRaidSignupsIndexRoute
  '/admin/schools': typeof AuthenticatedAdminSchoolsIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
  '/game-assist/guess-idiom': typeof AuthenticatedGameAssistGuessIdiomIndexRoute
  '/game-assist/minesweeper': typeof AuthenticatedGameAssistMinesweeperIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/forbidden/': typeof ForbiddenIndexRoute
  '/login/': typeof LoginIndexRoute
  '/_authenticated/raid-run/$id': typeof AuthenticatedRaidRunIdRoute
  '/_authenticated/raid-run/': typeof AuthenticatedRaidRunIndexRoute
  '/_authenticated/admin/app-settings/': typeof AuthenticatedAdminAppSettingsIndexRoute
  '/_authenticated/admin/game-dungeons/': typeof AuthenticatedAdminGameDungeonsIndexRoute
  '/_authenticated/admin/game-expansions/': typeof AuthenticatedAdminGameExpansionsIndexRoute
  '/_authenticated/admin/game-items/': typeof AuthenticatedAdminGameItemsIndexRoute
  '/_authenticated/admin/game-servers/': typeof AuthenticatedAdminGameServersIndexRoute
  '/_authenticated/admin/idioms/': typeof AuthenticatedAdminIdiomsIndexRoute
  '/_authenticated/admin/kungfus/': typeof AuthenticatedAdminKungfusIndexRoute
  '/_authenticated/admin/raid-runs/': typeof AuthenticatedAdminRaidRunsIndexRoute
  '/_authenticated/admin/raid-signups/': typeof AuthenticatedAdminRaidSignupsIndexRoute
  '/_authenticated/admin/schools/': typeof AuthenticatedAdminSchoolsIndexRoute
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/_authenticated/game-assist/guess-idiom/': typeof AuthenticatedGameAssistGuessIdiomIndexRoute
  '/_authenticated/game-assist/minesweeper/': typeof AuthenticatedGameAssistMinesweeperIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forbidden/'
    | '/login/'
    | '/raid-run/$id'
    | '/raid-run/'
    | '/admin/app-settings/'
    | '/admin/game-dungeons/'
    | '/admin/game-expansions/'
    | '/admin/game-items/'
    | '/admin/game-servers/'
    | '/admin/idioms/'
    | '/admin/kungfus/'
    | '/admin/raid-runs/'
    | '/admin/raid-signups/'
    | '/admin/schools/'
    | '/admin/users/'
    | '/game-assist/guess-idiom/'
    | '/game-assist/minesweeper/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/'
    | '/forbidden'
    | '/login'
    | '/raid-run/$id'
    | '/raid-run'
    | '/admin/app-settings'
    | '/admin/game-dungeons'
    | '/admin/game-expansions'
    | '/admin/game-items'
    | '/admin/game-servers'
    | '/admin/idioms'
    | '/admin/kungfus'
    | '/admin/raid-runs'
    | '/admin/raid-signups'
    | '/admin/schools'
    | '/admin/users'
    | '/game-assist/guess-idiom'
    | '/game-assist/minesweeper'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/admin'
    | '/_authenticated/'
    | '/forbidden/'
    | '/login/'
    | '/_authenticated/raid-run/$id'
    | '/_authenticated/raid-run/'
    | '/_authenticated/admin/app-settings/'
    | '/_authenticated/admin/game-dungeons/'
    | '/_authenticated/admin/game-expansions/'
    | '/_authenticated/admin/game-items/'
    | '/_authenticated/admin/game-servers/'
    | '/_authenticated/admin/idioms/'
    | '/_authenticated/admin/kungfus/'
    | '/_authenticated/admin/raid-runs/'
    | '/_authenticated/admin/raid-signups/'
    | '/_authenticated/admin/schools/'
    | '/_authenticated/admin/users/'
    | '/_authenticated/game-assist/guess-idiom/'
    | '/_authenticated/game-assist/minesweeper/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ForbiddenIndexRoute: typeof ForbiddenIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/forbidden/': {
      id: '/forbidden/'
      path: '/forbidden'
      fullPath: '/forbidden/'
      preLoaderRoute: typeof ForbiddenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/raid-run/': {
      id: '/_authenticated/raid-run/'
      path: '/raid-run'
      fullPath: '/raid-run/'
      preLoaderRoute: typeof AuthenticatedRaidRunIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/raid-run/$id': {
      id: '/_authenticated/raid-run/$id'
      path: '/raid-run/$id'
      fullPath: '/raid-run/$id'
      preLoaderRoute: typeof AuthenticatedRaidRunIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/app-settings/': {
      id: '/_authenticated/admin/app-settings/'
      path: '/app-settings'
      fullPath: '/admin/app-settings/'
      preLoaderRoute: typeof AuthenticatedAdminAppSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/game-dungeons/': {
      id: '/_authenticated/admin/game-dungeons/'
      path: '/game-dungeons'
      fullPath: '/admin/game-dungeons/'
      preLoaderRoute: typeof AuthenticatedAdminGameDungeonsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/game-expansions/': {
      id: '/_authenticated/admin/game-expansions/'
      path: '/game-expansions'
      fullPath: '/admin/game-expansions/'
      preLoaderRoute: typeof AuthenticatedAdminGameExpansionsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/game-items/': {
      id: '/_authenticated/admin/game-items/'
      path: '/game-items'
      fullPath: '/admin/game-items/'
      preLoaderRoute: typeof AuthenticatedAdminGameItemsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/game-servers/': {
      id: '/_authenticated/admin/game-servers/'
      path: '/game-servers'
      fullPath: '/admin/game-servers/'
      preLoaderRoute: typeof AuthenticatedAdminGameServersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/idioms/': {
      id: '/_authenticated/admin/idioms/'
      path: '/idioms'
      fullPath: '/admin/idioms/'
      preLoaderRoute: typeof AuthenticatedAdminIdiomsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/kungfus/': {
      id: '/_authenticated/admin/kungfus/'
      path: '/kungfus'
      fullPath: '/admin/kungfus/'
      preLoaderRoute: typeof AuthenticatedAdminKungfusIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/raid-runs/': {
      id: '/_authenticated/admin/raid-runs/'
      path: '/raid-runs'
      fullPath: '/admin/raid-runs/'
      preLoaderRoute: typeof AuthenticatedAdminRaidRunsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/raid-signups/': {
      id: '/_authenticated/admin/raid-signups/'
      path: '/raid-signups'
      fullPath: '/admin/raid-signups/'
      preLoaderRoute: typeof AuthenticatedAdminRaidSignupsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/schools/': {
      id: '/_authenticated/admin/schools/'
      path: '/schools'
      fullPath: '/admin/schools/'
      preLoaderRoute: typeof AuthenticatedAdminSchoolsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/game-assist/guess-idiom/': {
      id: '/_authenticated/game-assist/guess-idiom/'
      path: '/game-assist/guess-idiom'
      fullPath: '/game-assist/guess-idiom/'
      preLoaderRoute: typeof AuthenticatedGameAssistGuessIdiomIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/game-assist/minesweeper/': {
      id: '/_authenticated/game-assist/minesweeper/'
      path: '/game-assist/minesweeper'
      fullPath: '/game-assist/minesweeper/'
      preLoaderRoute: typeof AuthenticatedGameAssistMinesweeperIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAppSettingsIndexRoute: typeof AuthenticatedAdminAppSettingsIndexRoute
  AuthenticatedAdminGameDungeonsIndexRoute: typeof AuthenticatedAdminGameDungeonsIndexRoute
  AuthenticatedAdminGameExpansionsIndexRoute: typeof AuthenticatedAdminGameExpansionsIndexRoute
  AuthenticatedAdminGameItemsIndexRoute: typeof AuthenticatedAdminGameItemsIndexRoute
  AuthenticatedAdminGameServersIndexRoute: typeof AuthenticatedAdminGameServersIndexRoute
  AuthenticatedAdminIdiomsIndexRoute: typeof AuthenticatedAdminIdiomsIndexRoute
  AuthenticatedAdminKungfusIndexRoute: typeof AuthenticatedAdminKungfusIndexRoute
  AuthenticatedAdminRaidRunsIndexRoute: typeof AuthenticatedAdminRaidRunsIndexRoute
  AuthenticatedAdminRaidSignupsIndexRoute: typeof AuthenticatedAdminRaidSignupsIndexRoute
  AuthenticatedAdminSchoolsIndexRoute: typeof AuthenticatedAdminSchoolsIndexRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAppSettingsIndexRoute:
      AuthenticatedAdminAppSettingsIndexRoute,
    AuthenticatedAdminGameDungeonsIndexRoute:
      AuthenticatedAdminGameDungeonsIndexRoute,
    AuthenticatedAdminGameExpansionsIndexRoute:
      AuthenticatedAdminGameExpansionsIndexRoute,
    AuthenticatedAdminGameItemsIndexRoute:
      AuthenticatedAdminGameItemsIndexRoute,
    AuthenticatedAdminGameServersIndexRoute:
      AuthenticatedAdminGameServersIndexRoute,
    AuthenticatedAdminIdiomsIndexRoute: AuthenticatedAdminIdiomsIndexRoute,
    AuthenticatedAdminKungfusIndexRoute: AuthenticatedAdminKungfusIndexRoute,
    AuthenticatedAdminRaidRunsIndexRoute: AuthenticatedAdminRaidRunsIndexRoute,
    AuthenticatedAdminRaidSignupsIndexRoute:
      AuthenticatedAdminRaidSignupsIndexRoute,
    AuthenticatedAdminSchoolsIndexRoute: AuthenticatedAdminSchoolsIndexRoute,
    AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedRaidRunIdRoute: typeof AuthenticatedRaidRunIdRoute
  AuthenticatedRaidRunIndexRoute: typeof AuthenticatedRaidRunIndexRoute
  AuthenticatedGameAssistGuessIdiomIndexRoute: typeof AuthenticatedGameAssistGuessIdiomIndexRoute
  AuthenticatedGameAssistMinesweeperIndexRoute: typeof AuthenticatedGameAssistMinesweeperIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedRaidRunIdRoute: AuthenticatedRaidRunIdRoute,
  AuthenticatedRaidRunIndexRoute: AuthenticatedRaidRunIndexRoute,
  AuthenticatedGameAssistGuessIdiomIndexRoute:
    AuthenticatedGameAssistGuessIdiomIndexRoute,
  AuthenticatedGameAssistMinesweeperIndexRoute:
    AuthenticatedGameAssistMinesweeperIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ForbiddenIndexRoute: ForbiddenIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
