import { env } from '@api/infrastructure/config/env';
import { account, session, user, verification } from '@sidui/db';
import { betterAuth } from 'better-auth';
import { drizzleAdapter } from 'better-auth/adapters/drizzle';
import { admin, openAPI } from 'better-auth/plugins';
import { db } from './db';

export const auth = betterAuth({
  database: drizzleAdapter(db, {
    provider: 'pg',
    schema: { user, session, account, verification },
  }),
  trustedOrigins: [env.FRONTEND_URL],
  emailAndPassword: { enabled: true },
  session: {
    expiresIn: 60 * 60 * 24 * 7,
    updateAge: 60 * 60 * 24,
    cookieCache: {
      enabled: true,
      maxAge: 60 * 60 * 24,
      strategy: 'jwt',
    },
  },
  plugins: [openAPI(), admin()],
});

let _schema: ReturnType<typeof auth.api.generateOpenAPISchema>;
const getSchema = async () => (_schema ??= auth.api.generateOpenAPISchema());
export const OpenAPI = {
  getPaths: (prefix = '/api/auth') =>
    getSchema().then(({ paths }) => {
      const reference: typeof paths = Object.create(null);
      for (const path of Object.keys(paths)) {
        const key = prefix + path;
        reference[key] = paths[path];
        for (const method of Object.keys(paths[path])) {
          // biome-ignore lint/suspicious/noExplicitAny: Code generated by Better Auth
          const operation = (reference[key] as any)[method];
          operation.tags = ['Better Auth'];
        }
      }
      return reference;
      // biome-ignore lint/suspicious/noExplicitAny: Code generated by Better Auth
    }) as Promise<any>,
  // biome-ignore lint/suspicious/noExplicitAny: Code generated by Better Auth
  components: getSchema().then(({ components }) => components) as Promise<any>,
} as const;

export const roleUser = 'user';
export const roleAdmin = 'admin';

export const authProviders = ['credential'] as const;

export type AuthProvider = (typeof authProviders)[number];

export const normalizeProviders = (providerIds: string[]): AuthProvider[] => {
  const normalized = new Set<AuthProvider>();
  for (const providerId of providerIds) {
    if (authProviders.includes(providerId as AuthProvider)) {
      normalized.add(providerId as AuthProvider);
    }
  }
  return [...normalized];
};
