import { describe, expect, it } from 'bun:test';
import { ERROR_CODES } from '@api/shared/exception/error-code';

describe('ERROR_CODES', () => {
  it('exposes stable string codes', () => {
    expect(ERROR_CODES.SUCCESS).toBe('SUCCESS');
    expect(ERROR_CODES.IDIOM_NOT_FOUND).toBe('IDIOM_NOT_FOUND');
    expect(ERROR_CODES.USER_NOT_FOUND).toBe('USER_NOT_FOUND');
    expect(ERROR_CODES.USER_INVALID_PASSWORD).toBe('USER_INVALID_PASSWORD');
    expect(ERROR_CODES.USER_AVATAR_INVALID).toBe('USER_AVATAR_INVALID');
    expect(ERROR_CODES.USER_SESSION_REFRESH_FAILED).toBe(
      'USER_SESSION_REFRESH_FAILED',
    );
    expect(ERROR_CODES.STORAGE_UPLOAD_FAILED).toBe('STORAGE_UPLOAD_FAILED');
    expect(ERROR_CODES.SCHOOL_NOT_FOUND).toBe('SCHOOL_NOT_FOUND');
    expect(ERROR_CODES.KUNGFU_NOT_FOUND).toBe('KUNGFU_NOT_FOUND');
    expect(ERROR_CODES.GAME_ITEM_REPLACE_SAME_ITEM).toBe(
      'GAME_ITEM_REPLACE_SAME_ITEM',
    );
    expect(ERROR_CODES.IDION_DB_BROKEN_DATA).toBe('IDION_DB_BROKEN_DATA');
    expect(ERROR_CODES.RAID_RUN_DUNGEON_NOT_FOUND).toBe(
      'RAID_RUN_DUNGEON_NOT_FOUND',
    );
    expect(ERROR_CODES.RAID_RUN_NOT_FOUND).toBe('RAID_RUN_NOT_FOUND');
    expect(ERROR_CODES.RAID_RUN_WAGE_INVALID).toBe('RAID_RUN_WAGE_INVALID');
    expect(ERROR_CODES.RAID_RUN_STATUS_TRANSITION_INVALID).toBe(
      'RAID_RUN_STATUS_TRANSITION_INVALID',
    );
    expect(ERROR_CODES.RAID_RUN_SIGNUP_NOT_FOUND).toBe(
      'RAID_RUN_SIGNUP_NOT_FOUND',
    );
    expect(ERROR_CODES.RAID_RUN_INCOME_CHART_DUNGEON_INVALID).toBe(
      'RAID_RUN_INCOME_CHART_DUNGEON_INVALID',
    );
    expect(ERROR_CODES.RAID_LOOT_NOT_FOUND).toBe('RAID_LOOT_NOT_FOUND');
    expect(ERROR_CODES.APP_SETTING_KEY_INVALID).toBe('APP_SETTING_KEY_INVALID');
    expect(ERROR_CODES.APP_SETTING_VALUE_INVALID).toBe(
      'APP_SETTING_VALUE_INVALID',
    );
  });
});
