export const ERROR_CODES = {
  SUCCESS: 'SUCCESS',
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',

  // Idiom
  IDIOM_PARSE_PINYIN_FAILED: 'IDIOM_PARSE_PINYIN_FAILED',
  IDIOM_ALREADY_EXISTS: 'IDIOM_ALREADY_EXISTS',
  IDIOM_NOT_FOUND: 'IDIOM_NOT_FOUND',
  IDIOM_CSV_EMPTY_OR_MISSING_HEADERS: 'IDIOM_CSV_EMPTY_OR_MISSING_HEADERS',
  IDIOM_CSV_MISSING_TEXT_COLUMN: 'IDIOM_CSV_MISSING_TEXT_COLUMN',
  IDIOM_CSV_EMPTY: 'IDIOM_CSV_EMPTY',
  IDIOM_TEXT_EMPTY: 'IDIOM_TEXT_EMPTY',
  IDIOM_PINYIN_LENGTH_MISMATCH: 'IDIOM_PINYIN_LENGTH_MISMATCH',
  IDIOM_UNRECOGNIZED_PINYIN_TONE: 'IDIOM_UNRECOGNIZED_PINYIN_TONE',
  IDION_DB_BROKEN_DATA: 'IDION_DB_BROKEN_DATA',

  // User
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_EMAIL_ALREADY_EXISTS: 'USER_EMAIL_ALREADY_EXISTS',
  USER_CANNOT_OPERATE_SELF: 'USER_CANNOT_OPERATE_SELF',
  USER_CANNOT_MODIFY_ADMIN: 'USER_CANNOT_MODIFY_ADMIN',
  USER_INVALID_PASSWORD: 'USER_INVALID_PASSWORD',
  USER_AVATAR_INVALID: 'USER_AVATAR_INVALID',
  USER_SESSION_REFRESH_FAILED: 'USER_SESSION_REFRESH_FAILED',
  STORAGE_UPLOAD_FAILED: 'STORAGE_UPLOAD_FAILED',

  // School
  SCHOOL_NOT_FOUND: 'SCHOOL_NOT_FOUND',
  SCHOOL_NAME_ALREADY_EXISTS: 'SCHOOL_NAME_ALREADY_EXISTS',
  SCHOOL_IN_USE: 'SCHOOL_IN_USE',

  // Kungfu
  KUNGFU_NOT_FOUND: 'KUNGFU_NOT_FOUND',
  KUNGFU_NAME_ALREADY_EXISTS: 'KUNGFU_NAME_ALREADY_EXISTS',
  KUNGFU_IN_USE: 'KUNGFU_IN_USE',

  // Game server
  GAME_SERVER_NOT_FOUND: 'GAME_SERVER_NOT_FOUND',
  GAME_SERVER_ID_ALREADY_EXISTS: 'GAME_SERVER_ID_ALREADY_EXISTS',
  GAME_SERVER_ZONE_NAME_ALREADY_EXISTS: 'GAME_SERVER_ZONE_NAME_ALREADY_EXISTS',
  GAME_SERVER_IN_USE: 'GAME_SERVER_IN_USE',

  // Game expansion
  GAME_EXPANSION_NOT_FOUND: 'GAME_EXPANSION_NOT_FOUND',
  GAME_EXPANSION_NAME_ALREADY_EXISTS: 'GAME_EXPANSION_NAME_ALREADY_EXISTS',
  GAME_EXPANSION_IN_USE: 'GAME_EXPANSION_IN_USE',
  GAME_EXPANSION_HAS_SEASONS: 'GAME_EXPANSION_HAS_SEASONS',
  GAME_EXPANSION_DATE_INVALID: 'GAME_EXPANSION_DATE_INVALID',
  GAME_EXPANSION_DATE_CONFLICTS_WITH_SEASONS:
    'GAME_EXPANSION_DATE_CONFLICTS_WITH_SEASONS',

  // Game season
  GAME_SEASON_NOT_FOUND: 'GAME_SEASON_NOT_FOUND',
  GAME_SEASON_NAME_ALREADY_EXISTS: 'GAME_SEASON_NAME_ALREADY_EXISTS',
  GAME_SEASON_IN_USE: 'GAME_SEASON_IN_USE',
  GAME_SEASON_DATE_INVALID: 'GAME_SEASON_DATE_INVALID',
  GAME_SEASON_DATE_OUTSIDE_EXPANSION: 'GAME_SEASON_DATE_OUTSIDE_EXPANSION',

  // Game dungeon
  GAME_DUNGEON_NOT_FOUND: 'GAME_DUNGEON_NOT_FOUND',
  GAME_DUNGEON_ALREADY_EXISTS: 'GAME_DUNGEON_ALREADY_EXISTS',
  GAME_DUNGEON_IN_USE: 'GAME_DUNGEON_IN_USE',
  GAME_DUNGEON_SEASON_EXPANSION_MISMATCH:
    'GAME_DUNGEON_SEASON_EXPANSION_MISMATCH',

  // Game item
  GAME_ITEM_NOT_FOUND: 'GAME_ITEM_NOT_FOUND',
  GAME_ITEM_NAME_ALREADY_EXISTS: 'GAME_ITEM_NAME_ALREADY_EXISTS',
  GAME_ITEM_GAME_ID_ALREADY_EXISTS: 'GAME_ITEM_GAME_ID_ALREADY_EXISTS',
  GAME_ITEM_IN_USE: 'GAME_ITEM_IN_USE',
  GAME_ITEM_REPLACE_SAME_ITEM: 'GAME_ITEM_REPLACE_SAME_ITEM',

  // Raid run
  RAID_RUN_TIME_INVALID: 'RAID_RUN_TIME_INVALID',
  RAID_RUN_DUNGEON_NOT_FOUND: 'RAID_RUN_DUNGEON_NOT_FOUND',
  RAID_RUN_PLAYER_LIMIT_EXCEEDED: 'RAID_RUN_PLAYER_LIMIT_EXCEEDED',
  RAID_RUN_GROUP_NUMBER_INVALID: 'RAID_RUN_GROUP_NUMBER_INVALID',
  RAID_RUN_RESERVED_TANK_MISMATCH: 'RAID_RUN_RESERVED_TANK_MISMATCH',
  RAID_RUN_RESERVED_HEALER_MISMATCH: 'RAID_RUN_RESERVED_HEALER_MISMATCH',
  RAID_RUN_RESERVED_DPS_MISMATCH: 'RAID_RUN_RESERVED_DPS_MISMATCH',
  RAID_RUN_RESERVED_BOSS_MISMATCH: 'RAID_RUN_RESERVED_BOSS_MISMATCH',
  RAID_RUN_DUPLICATE_POSITION: 'RAID_RUN_DUPLICATE_POSITION',
  RAID_RUN_SERVER_NOT_FOUND: 'RAID_RUN_SERVER_NOT_FOUND',
  RAID_RUN_SCHOOL_NOT_FOUND: 'RAID_RUN_SCHOOL_NOT_FOUND',
  RAID_RUN_KUNGFU_NOT_FOUND: 'RAID_RUN_KUNGFU_NOT_FOUND',
  RAID_RUN_KUNGFU_SCHOOL_MISMATCH: 'RAID_RUN_KUNGFU_SCHOOL_MISMATCH',
  RAID_RUN_LEADER_COUNT_INVALID: 'RAID_RUN_LEADER_COUNT_INVALID',
  RAID_RUN_DARK_RUN_COUNT_INVALID: 'RAID_RUN_DARK_RUN_COUNT_INVALID',
  RAID_RUN_FORMATION_CORE_INVALID: 'RAID_RUN_FORMATION_CORE_INVALID',
  RAID_RUN_NOT_FOUND: 'RAID_RUN_NOT_FOUND',
  RAID_RUN_WAGE_INVALID: 'RAID_RUN_WAGE_INVALID',
  RAID_RUN_STATUS_TRANSITION_INVALID: 'RAID_RUN_STATUS_TRANSITION_INVALID',
  RAID_RUN_SIGNUP_NOT_FOUND: 'RAID_RUN_SIGNUP_NOT_FOUND',
  RAID_RUN_CALENDAR_RANGE_INVALID: 'RAID_RUN_CALENDAR_RANGE_INVALID',
  RAID_RUN_INCOME_CHART_DUNGEON_INVALID:
    'RAID_RUN_INCOME_CHART_DUNGEON_INVALID',

  // Raid loot
  RAID_LOOT_NOT_FOUND: 'RAID_LOOT_NOT_FOUND',

  // App setting
  APP_SETTING_KEY_INVALID: 'APP_SETTING_KEY_INVALID',
  APP_SETTING_VALUE_INVALID: 'APP_SETTING_VALUE_INVALID',

  // LLM model price
  LLM_MODEL_PRICE_NOT_FOUND: 'LLM_MODEL_PRICE_NOT_FOUND',
  LLM_MODEL_PRICE_CURRENT_EXISTS: 'LLM_MODEL_PRICE_CURRENT_EXISTS',
  LLM_MODEL_PRICE_NOT_CURRENT: 'LLM_MODEL_PRICE_NOT_CURRENT',
  LLM_MODEL_PRICE_CANNOT_DELETE: 'LLM_MODEL_PRICE_CANNOT_DELETE',
  LLM_MODEL_PRICE_CANNOT_EDIT: 'LLM_MODEL_PRICE_CANNOT_EDIT',
  LLM_MODEL_PRICE_EFFECTIVE_FROM_INVALID:
    'LLM_MODEL_PRICE_EFFECTIVE_FROM_INVALID',

  // Lyric song
  LYRIC_SONG_NOT_FOUND: 'LYRIC_SONG_NOT_FOUND',
  LYRIC_LINE_INVALID: 'LYRIC_LINE_INVALID',
  LYRIC_SONG_IMPORT_INVALID: 'LYRIC_SONG_IMPORT_INVALID',
  LYRIC_AI_UNAVAILABLE: 'LYRIC_AI_UNAVAILABLE',
} as const;
